language: node_js
node_js:
  - "4.1"
sudo: false

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip

before_script:
  - npm run before:test:chrome &
  - sleep 3

script:
  - npm run lint
  - npm test
